name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8']
        include:
          - python-version: '3.8'
            numpy-version: '1.21.4'
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          set VCPKG_BUILD_TYPE=release
          vcpkg install eigen3 cgal --triplet x64-windows
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          vcpkg version
          ls "C:\vcpkg\installed\x64-windows\bin\"
          python -m pip install --user numpy~=${{ matrix.numpy-version }}
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pip install --user -r .\ext\gudhi-deploy\build-requirements.txt
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
      - name: Build python wheel and install it
        run: |
          mkdir build
          cd ".\build\"
          cmake -DCMAKE_BUILD_TYPE=Release -DFORCE_EIGEN_DEFAULT_DENSE_INDEX_TYPE_TO_INT=ON -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          cd ".\src\python\"
          cp "C:\vcpkg\installed\x64-windows\bin\mpfr*.dll" ".\gudhi\"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          cp "C:\vcpkg\installed\x64-windows\bin\gmp*.dll" ".\gudhi\"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m build -n -w
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          ls ".\dist\"
          cd ".\dist\"
          Get-ChildItem *.whl | ForEach-Object{python -m pip install --user $_.Name}
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
      - name: Test python wheel
        run: |
          Get-Location
          dir
          python -m pip install --user  numpy --upgrade
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pip install --user pytest
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -c "import gudhi; print(gudhi.__version__)"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pytest -v ".\src\python\test\test_alpha_complex.py"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pytest -v ".\src\python\test\test_bottleneck_distance.py"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pytest -v ".\src\python\test\test_cubical_complex.py"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
          python -m pytest -v ".\src\python\test\test_rips_complex.py"
          IF %errorlevel% NEQ 0 exit /b %errorlevel%
      - name: Upload Windows python wheel
        uses: actions/upload-artifact@v4
        with:
          name: windows python wheel
          path: build/src/python/dist/*.whl
