name: pip build linux

on: [push, pull_request]

# Temporary workaround to allow node16
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    name: build pip wheel
    runs-on: ubuntu-latest
    # cf. https://github.com/GUDHI/gudhi-deploy/blob/main/Dockerfile_for_pip
    container: gudhi/pip_for_gudhi:2024.10.02
    steps:
      # Should use actions/checkout@v4, but requires node20, not available for quay.io/pypa/manylinux2014_x86_64
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build wheel for Python 3.13
        run: |
          mkdir build_313
          cd build_313
          cmake -DCMAKE_BUILD_TYPE=Release -DPython_EXECUTABLE=$PYTHON313/bin/python ..
          cd src/python
          $PYTHON313/bin/python -m build -n -w
          auditwheel repair dist/*.whl
      # NumPy 2.X is installed and guarantees ABI compatibility, test it with the minimal numpy version for python version
      - name: Install and test wheel for Python 3.13
        run: |
          $PYTHON313/bin/python -m pip install --user pytest build_313/src/python/dist/*.whl
          $PYTHON313/bin/python -m pip install numpy~=2.1.2
          $PYTHON313/bin/python -c "import gudhi; print(gudhi.__version__)"
          $PYTHON313/bin/python -m pytest -v src/python/test/test_alpha_complex.py
          $PYTHON313/bin/python -m pytest -v src/python/test/test_delaunay_complex.py
          $PYTHON313/bin/python -m pytest -v src/python/test/test_bottleneck_distance.py
          $PYTHON313/bin/python -m pytest -v src/python/test/test_cubical_complex.py
          $PYTHON313/bin/python -m pytest -v src/python/test/test_rips_complex.py
      - name: Upload linux python wheel
        # Should use actions/upload-artifact@v4, but requires node20, not available for quay.io/pypa/manylinux2014_x86_64
        uses: actions/upload-artifact@v3
        with:
          name: linux python wheel
          path: build_313/src/python/wheelhouse/*.whl
